# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategories_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品sku表', 'verbose_name_plural': '商品sku表'},
        ),
        migrations.AlterModelOptions(
            name='goodsunit',
            options={'verbose_name': '商品单位表', 'verbose_name_plural': '商品单位表'},
        ),
    ]
