# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='假删除')),
                ('nickname', models.CharField(max_length=32, verbose_name='用户名')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('gender', models.CharField(choices=[('男', 1), ('女', 2), ('保密', 3)], default=1, max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('school', models.CharField(max_length=50, verbose_name='学校')),
                ('location', models.CharField(max_length=50, verbose_name='地址')),
                ('hometown', models.CharField(max_length=50, verbose_name='家乡')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
    ]
