# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 08:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181120_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(default=14567675432, max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误!')], verbose_name='电话号码'),
            preserve_default=False,
        ),
    ]
