# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='head',
            field=models.ImageField(default='images/default.jpg', max_length=200, upload_to='img/%Y%m/%d', verbose_name='头像'),
        ),
    ]
